# Generated by Django 4.2.8 on 2024-02-20 17:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("offer", "0004_chatroom_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="room",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
        migrations.DeleteModel(
            name="ChatRoom",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
